trigger:
  - main

jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        # <-- SNIP BEGIN -->
        py39:
          python.version: '3.9'
          tox.env: py39
        # docs:
        #   python.version: '3.9'
        #   tox.env: docs
        # <-- SNIP END -->

    steps:
      - task: UsePythonVersion@0
        displayName: Get Python for Python tools.
        inputs:
          versionSpec: '3.9'
          addToPath: false
        name: pyTools

      - script: $(pyTools.pythonLocation)/bin/pip install --upgrade tox
        displayName: Install Python-based tools.

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
        displayName: Use cached Python $(python.version) for tests.

      - script: pip install -r webscrap-backend/requirements.txt --no-cache-dir
        displayName: 'Install requirements'
      - script: python webscrap-backend/debug.py

      - task: PublishPipelineArtifact@0
        displayName: Publish artifacts
        inputs:
          targetPath: webscrap-backend